services:
  http-proxy:
    build: .
    container_name: http-proxy
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"