services:
  game-proxy:
    build: .
    container_name: game-proxy
    restart: unless-stopped
    env_file:
      - .env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"